### ISSUE TITLE
Delegations!

### ISSUE THREAD

**Issue by dlorenc** [sigstore/root-signing#26]
I think we need to start adding support for delegations here so we can let other projects reuse this!

**Comment by asraa** [comment]
We should start preparing what the process for becoming a SigStore trust delegation before the second root signing refresh in October! Based on https://github.com/sigstore/fulcio/issues/122...

I think based on the proposal we may want to stage empty/minimal metadata in preparation for the next signing so that the process below can work.

### Delegation Process
Interested projects should use a pull-request based enrollment policy containing a configuration file in this repo. I don't think an issue is required first. The pull request would add a stub for the delegation's keys in the next staged `targets.json`:

```
  "delegations": {
   "keys": {
    "c8022fa1e9b9cb239a6b362bbdffa9649e61ad2cb699d2e4bc4fdf7930a0e64a": {
     "keyid_hash_algorithms": [
      "sha256",
      "sha512"
     ],
     "keytype": "ed25519",
     "keyval": {
      "public": "fcf224e55fa226056adf113ef1eb3d55e308b75b321c8c8316999d8c4fd9e0d9"
     },
     "scheme": "ed25519"
    }
   },
   "roles": [
    {
     "keyids": [
      "c8022fa1e9b9cb239a6b362bbdffa9649e61ad2cb699d2e4bc4fdf7930a0e64a"
     ],
     "name": "kubernetes",
     "paths": ["k8s.io/releases/*"],
     "threshold": 1
    }
   ]
  },
```

And it will also contain an empty delegated role file `kubernetes.json` that looks something like
```
{
 "signatures": [
  {
   "keyid": "c8022fa1e9b9cb239a6b362bbdffa9649e61ad2cb699d2e4bc4fdf7930a0e64a",
   "sig": "75b196a224fd200e46e738b1216b3316c5384f61083872f8d14b8b0a378b2344e64b1a6f1a89a711206a66a0b199d65ac0e30fe15ddbc4de89fa8ff645f99403"
  }
 ],
 "signed": {
  "_type": "targets",
  "expires": "2030-01-01T00:00:00Z",
  "spec_version": "1.0.0",
  "targets": {},
  "version": 1
 }
}
```

Trusted delegations can then update their delegation `project_name.json` with the targets they are signing through PRs whenever they want.

We'll have a default of 4 months for expiration until the next root signing event, so you'll need to opt-in every root-signing cycle (And maybe extend later?)

We'll need at least the following:
* Contact info (email address)
* Verify this email address
* Proof of public key ownership?

I think we'll also need a script to generate the stub. I can try to work on that but I think I'll need to add go-tuf repository tool support quickly.


cc @priyawadhwa

**Comment by Hayden-IO** [comment]
Delegations are supported.
