### ISSUE TITLE
Correct the generation of expirations for metadata

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#267]
**Description**

**Version**

the snapshot was generated with the wrong expiration) (Generate expiration as Now + 2/3 weeks)

**Comment by asraa** [comment]
This might have been because the `Init` step adds snapshot signers with default expiration (7 days) and THEN the `Snapshot` command changes it to 2 weeks. So if a rollback was done on init, then maybe the incorrect expiration came about. 

This PR will fix this uniformly in both places https://github.com/sigstore/root-signing/pull/276
