### ISSUE TITLE
[discussion] Retrieving fork point for the delegation

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#735]
**Question**

The delegation scripts relied on retrieving the fork point to compute the nonce (see https://github.com/sigstore/root-signing/issues/729). 

While this may change and the issue may have been caused by what we did below, we've encountered an inexplicable confusion and wanted to see if someone  could help understand the issue and come to an explanation.

Roughly what happened:
1. Upstream main was at commit [e342408c0db1bc9b1702c3443f858aad6bb3420f](https://github.com/sigstore/root-signing/commit/e342408c0db1bc9b1702c3443f858aad6bb3420f) when the `test-ceremony/2023-03-20` branch was created and the initialize PR was created.*
2. A PR was merged to upstream main https://github.com/sigstore/root-signing/commit/49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a
3. A PR was created from a checkout of `test-ceremony/2023-03-20`.
4. Running 
`git merge-base --fork-point origin/main PR_BRANCH`
`git merge-base --fork-point main PR_BRANCH`

would return different results (sometimes the expected common ancestor and sometimes no result)

@kommendorkapten Now, when I run 
```
GITHUB_USER=asraa ./scripts/dpop-verify.sh (734/733) registry.npmjs.org
```

I get the correct merge-base, the `e342408c0db1bc9b1702c3443f858aad6bb3420f` commit - and it errors out that the merge-based was computed to be your fork at the time's tip (`4d..`).

So I think we should:
1. Ensure that root-signing upstream tip is frozen when a new ceremony is initiated.
  * This will be the fork point of test-ceremony - so `--fork-point` won't return no result.
  * This will ensure that the delegator's fork matches sigstore/root-signing main so that the fork point that is created by the signer is the fork point with upstream's main too.

Sorry for not explaining this issue too much, at this point I can't quite reproduce.

The main question is:
* Why does `git merge-base --fork-point` produce different results with `origin/main` and `main`?
* Why does it return no result? Is it something to do with the new commit added in the meantime and a fork point is no longer safe to merge against?

* Side note: should initialize.yml just run on branch creation?

**Comment by kommendorkapten** [comment]
I just did a fresh clone of the repo, and then I ran the verify script, now I'm getting totally different results:
```shell
$ git merge-base --fork-point origin/main VERIFY
$ git merge-base --fork-point main VERIFY
$ git merge-base origin/main VERIFY
e342408c0db1bc9b1702c3443f858aad6bb3420f
$ git merge-base main VERIFY
e342408c0db1bc9b1702c3443f858aad6bb3420f
$
```

I.e with `--fork-point` included I don't get any result. 

`e3424...` is the expected merge base.

**Comment by kommendorkapten** [comment]
Reading the [docs](https://git-scm.com/docs/git-merge-base#_discussion_on_fork_point_mode) over and over again, I think I may understand what's happening

> Also, the remote-tracking branch you use the `--fork-point` mode with must be the one your topic forked from its tip. If you forked from an older commit than the tip, this mode would not find the fork point (imagine in the above sample history B0 did not exist, origin/master started at B1, moved to B2 and then B, and you forked your topic at origin/master^ when origin/master was B1; the shape of the history would be the same as above, without B0, and the parent of B1 is what `git merge-base origin/master topic` correctly finds, but the `--fork-point` mode will not, because it is not one of the commits that used to be at the tip of origin/master).

Especially this `If you forked from an older commit than the tip, this mode would not find the fork point ` is true, as when I ran the command the first time I did not have a fully updated `main`. I think this may caused a wrong (older) `fork-point` to be chosen. 

And then ` and the parent of B1 is what git merge-base origin/master topic correctly finds, but the --fork-point mode will not, because it is not one of the commits that used to be at the tip of origin/master).` may explain why `--fork-point` gives an empty result, as fork point wasn't the tip of origin/master when the branch was forked.

I will continue to see if I can get some consistent results.

edit: formatting fixes

**Comment by kommendorkapten** [comment]
I *think* understand this now, if the `main` branch is not up to date with `origin` when the ceremony branch (or the delegation branch) is created, fork-point may not be found. I reproduced it now, and I get consistent results:

```shell
$ git checkout test-ceremony/2023-03-20
branch 'test-ceremony/2023-03-20' set up to track 'upstream/test-ceremony/2023-03-20'.
Switched to a new branch 'test-ceremony/2023-03-20'

$ git checkout -b test_fork_fsn
Switched to a new branch 'test_fork_fsn'
$ git merge-base --fork-point origin/main test_fork_fsn
$
$ git merge-base --fork-point main test_fork_fsn
$

$ git merge-base  origin/main test_fork_fsn
e342408c0db1bc9b1702c3443f858aad6bb3420f
$ git merge-base  main test_fork_fsn
e342408c0db1bc9b1702c3443f858aad6bb3420f
```

Here we can clearly see that `--fork-point` gives an empty result, as when I created the `test_fork_fsn` branch, it was not based from tip of `main` (`main` have had commits since the `test-ceremony/2023-03-20` branch was created). 
But if we run the command without `--fork-point` we get the correct merge-base, `e3424` which is the commit in `main` we branched `test-ceremony/2023-03-20` from.

If we make sure `main` is up to date and retry the steps:
```shell
$ git checkout -b test-ceremony-local/2023-03-20
Switched to a new branch 'test-ceremony-local/2023-03-20'
# add a commit to "stage root"
$ git checkout -b test_fork_fsn_2
Switched to a new branch 'test_fork_fsn_2'
$ git merge-base --fork-point origin/main test_fork_fsn_2
49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a
$ git merge-base --fork-point main test_fork_fsn_2
49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a
$ git merge-base origin/main test_fork_fsn_2
49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a
$ git merge-base main test_fork_fsn_2
49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a
```

And now looking at `git log` all looks in order:
```shell
commit 948f59135a81a22aa417c17c49ba856ba3cde24d (HEAD -> test_fork_fsn_2, test-ceremony-local/2023-03-20)
Author: Fredrik Skogman <kommendorkapten@github.com>
Date:   Tue Mar 21 08:57:13 2023 +0100

    added a test file (simulate new commit with staged root).

    Signed-off-by: Fredrik Skogman <kommendorkapten@github.com>

commit 49896d7885e9ed2a1e6d530ecc98f87d6b54dd2a (upstream/main, origin/main, main)
Author: asraa <asraa@google.com>
Date:   Mon Mar 20 11:35:46 2023 -0500

    feat: add delegated target validation to ./scripts/verify.sh (#731)

    Fixes #705
...
```

**Comment by kommendorkapten** [comment]
It's even possible to simplify this just on the ceremony branch:
```shell 
$ git merge-base --fork-point origin/main test-ceremony/2023-03-20
$
$ git merge-base --fork-point main test-ceremony/2023-03-20
e342408c0db1bc9b1702c3443f858aad6bb3420f
$ git merge-base origin/main test-ceremony/2023-03-20
e342408c0db1bc9b1702c3443f858aad6bb3420f
$ git merge-base main test-ceremony/2023-03-20
e342408c0db1bc9b1702c3443f858aad6bb3420f
```

**Comment by derrickstolee** [comment]
[The `--fork-point` option](https://git-scm.com/docs/git-merge-base#Documentation/git-merge-base.txt---fork-point) uses the reflog instead of the commit history from the tip of the reference. Remote refs, such as `origin/main`, do not have a reflog, so the command returns with an exit code of 1, signalling a failure.

Git could probably do a better job of writing an error message to `stderr` in this kind of failure, saying something like "`--fork-point` requires a reflog" instead of exiting with code 1 and no message.

Personally, I do not recommend using `--fork-point` since your local reflog will not match the server's, so any benefit you hope to get from using that option will not be exact to the server's operation.
