### ISSUE TITLE
Regenerate staging with trusted_root.json

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#755]
**Description**

sigstore-js and sigstore-python now expect this file, so we should regenerate staging. Also would be a good time to do https://github.com/sigstore/root-signing/issues/416#issuecomment-1462473728, creating a permanent key and delegation script

**Comment by asraa** [comment]
Do you want to perform a ceremony on the staging branch with a new staging folder? that's probably the easiest way to for #416 and achieve this, since doing the actions on this repository will mirror the targets we're planning to use.

You might need to finagle the scripts to customize the REPO var from the hard-coded `repository` but the reusable workflow we have could work for this after that, and you can use the test key in testdata.

(This way you can just exercise the existing flows -- since the npm delegation workflows aren't OSS yet, you would need to run the documented scripts to generate those PRs https://github.com/sigstore/root-signing/blob/main/playbooks/ORCHESTRATION.md#step-3-add-delegation-optional).

**Comment by Hayden-IO** [comment]
Yea, given the number of additional files needed now, doing a ceremony would likely be the simplest

**Comment by asraa** [comment]
SG - we even have test HSM keys https://github.com/sigstore/root-signing/tree/main/tests/test_data/10550341

so you can use those to populate a staging folder's keys, and then run Init on that.

**Comment by asraa** [comment]
I can just push something to get it working locally in about 5 min, since this is probably somewhat high priority for clients.

Creating workflows for staing repo can happen later, all the keys are in this repository.

**Comment by Hayden-IO** [comment]
That would be great! If you can just note any manual steps you do, we can get those automated later

**Comment by asraa** [comment]
Yeah, it's all documented in orchestration, but I'll write it up in the PR.
